### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by HappyDay-design** [Guojyjy/CoTV#1]
Thank you very much for sharing your models!
I can implement your model with Sumo 1.17.0 instead of 1.10.0

![image](https://github.com/Guojyjy/CoTV/assets/82990411/2933b345-d6f0-4f62-8b16-bb82eb025ea8)

I will cite your papers in my manuscript. 

echo $DISPLAY
xhost +
sudo docker container run -it --env="DISPLAY" --net=host <images_ID>

**Comment by Guojyjy** [comment]
Glad to hear that. Thank you!

**Comment by Gavin-Tao** [comment]
May I ask which version of Ubuntu you are using?

**Comment by HappyDay-design** [comment]
Ubuntu 18

**Comment by Gavin-Tao** [comment]
Please be aware that this email box is not available now. If you have any contact with me, please send your emails to my current email box ***@***.***).

**Comment by HappyDay-design** [comment]
> 



> May I ask which version of Ubuntu you are using?
Ubuntu 18
