### ISSUE TITLE
CoTV_grid  example can't use sumo strategy playback

### ISSUE THREAD

**Issue by Linda598-prog** [Guojyjy/CoTV#12]
in ubuntu
Loading configuration... done.
***Starting server on port 48535 ***
Loading net-file from '/tmp/flow/debug/cfg/CoTV_1x1grid_20240522-1050491716346249.6291587.net.xml'... done (2ms).
Loading additional-files from '/tmp/flow/debug/cfg/CoTV_1x1grid_20240522-1050491716346249.6291587.add.xml'... done (23ms).
Loading done.
Simulation started with time: 0.00
Error: Could not build output file 'None/CoTV_1x1grid_20240522-1050491716346249.6291587-3-ssm.xml' (没有那个文件或目录).
Quitting (on error).
![2024-05-20 15-13-00 的屏幕截图](https://github.com/Guojyjy/CoTV/assets/164609695/8e44fd45-8961-4500-a69b-cd6ce19f2bf6)
how to solve this issue

**Comment by Linda598-prog** [comment]
Hi Dr.Guo,

I'm running into the above issue when I'm using SUMO to visualize CoTV grid. The command I'm using _is _python _flow/visualizer_rllib.py /home/yl/ray_results/CoTV_1x1grid/PPO_CoTV-v1_adf813ac-2024-05-16_14-08-131egbi7e6 10  --horizon 20 , are you experiencing this kind of problem？and I'm looking forward to your guidance. 

Thank you and good wishes.

**Comment by sunshine147896** [comment]
Thank you,  I have already solved this problem.
