### ISSUE TITLE
Install flow issue

### ISSUE THREAD

**Issue by Gavin-Tao** [Guojyjy/CoTV#2]
(flow) E:\CoTV\flow>python setup.py develop
D:\Anaconda\envs\flow\lib\site-packages\setuptools\dist.py:510: InformationOnly: Normalizing '0.5.0.dev' to '0.5.0.dev0'
  self._validate_version(self.metadata.version)
running develop
D:\Anaconda\envs\flow\lib\site-packages\setuptools\command\develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
D:\Anaconda\envs\flow\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing flow.egg-info\PKG-INFO
writing dependency_links to flow.egg-info\dependency_links.txt
writing requirements to flow.egg-info\requires.txt
writing top-level names to flow.egg-info\top_level.txt
reading manifest file 'flow.egg-info\SOURCES.txt'
adding license file 'LICENSE.md'
writing manifest file 'flow.egg-info\SOURCES.txt'
running build_ext
error: [WinError 2] The system cannot find the file specified

**Comment by Guojyjy** [comment]
Hi, if you have an issue in Flow Installation, [Local Installation of Flow](https://flow.readthedocs.io/en/latest/flow_setup.html#) may be helpful to successfully install the Flow, first then run CoTV.

Have you tried `pip install -e .`? Does it work?

```shell
python setup.py develop # if the conda install fails, try the next command to install the requirements using pip
pip install -e . # install flow within the environment
```

I also provide the CoTV docker image, please try it following the instruction: [README: Virtual installation](https://github.com/Guojyjy/CoTV#virtual-installation).

BTW, My Ubuntu version is Ubuntu 20.04.2 LTS.

**Comment by Gavin-Tao** [comment]
Thanks so much for your prompt reply. Problems have been solved. Cool!
