### ISSUE TITLE
Warning: Vehicle 'flow_00.0' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=26.00.

### ISSUE THREAD

**Issue by Gavin-Tao** [Guojyjy/CoTV#3]
Dear author,

Thanks very much for your sharing. When I run your codes, the terminal shows the below warning:

(pid=10947) Warning: Vehicle 'flow_00.0' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=26.00.
(pid=10938) Warning: Vehicle 'flow_20.1' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=79.00.
(pid=10951) Warning: Vehicle 'flow_10.5' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=99.00.
(pid=10950) Warning: Vehicle 'flow_10.5' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=98.00.
(pid=10951) Warning: Vehicle 'flow_20.3' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=106.00.
(pid=10955) Warning: Vehicle 'flow_20.5' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=130.00.
(pid=10939) Warning: Vehicle 'flow_10.9' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=157.00.
(pid=10941) Warning: Vehicle 'flow_20.8' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=169.00.
(pid=10940) Warning: Vehicle 'flow_30.5' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=177.00.
(pid=10944) Warning: Vehicle 'flow_30.5' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=176.00.
(pid=10943) Warning: Vehicle 'flow_30.5' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=176.00.
(pid=10944) Warning: Vehicle 'flow_20.9' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=180.00.
(pid=10940) Warning: Vehicle 'flow_20.10' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=190.00.
(pid=10946) Warning: Vehicle 'flow_20.13' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=232.00.
(pid=10949) Warning: Vehicle 'flow_20.14' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=246.00.
(pid=10951) Warning: Vehicle 'flow_20.16' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=269.00.
(pid=10944) Warning: Vehicle 'flow_20.17' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=280.00.
(pid=10945) Warning: Vehicle 'flow_20.19' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=305.00.
(pid=10950) Warning: Vehicle 'flow_20.20' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=317.00.
(pid=10944) Warning: Vehicle 'flow_30.13' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=328.00.
(pid=10951) Warning: Vehicle 'flow_30.13' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=330.00.
(pid=10941) Warning: Vehicle 'flow_20.22' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=342.00.

May I ask if you also encounter these warnings when running the code and whether the warnings will affect the CoTV's performance?

**Comment by Gavin-Tao** [comment]
when I run this experiment: python examples/train_ppo.py CoTV_Dublin

**Comment by huigeopencv** [comment]
when you run this experiment: python examples/train_ppo.py CoTV_grid --num_steps 150, have you encountered this error? "Error: Mismatching phase size in tls  center0  , program  online". 
How should this BUG be fixed? Thank you!

**Comment by Gavin-Tao** [comment]
Please be aware that this email box is not available now. If you have any contact with me, please send your emails to my current email box ***@***.***).

**Comment by Gavin-Tao** [comment]
> when you run this experiment: python examples/train_ppo.py CoTV_grid --num_steps 150, have you encountered this error? "Error: Mismatching phase size in tls center0 , program online". How should this BUG be fixed? Thank you!

I did not meet this problem. can you send email to me taoxw19 AT 163 DOT com.

**Comment by Guojyjy** [comment]
About the emergency brake, the instantaneous accelerations of vehicles are recorded in the output file: _emission.csv_, with the column "**realized_accel**".

I processed over 100 output files, _emission.csv_, of CoTV after training convergence under Dublin scenario. The result shows that there is no vehicle deceleration exceeding 9 m/s^2.

Could you show me more experiment details about the emergency brake?

**Comment by Gavin-Tao** [comment]
Please be aware that this email box is not available now. If you have any contact with me, please send your emails to my current email box ***@***.***).

**Comment by Guojyjy** [comment]
> when you run this experiment: python examples/train_ppo.py CoTV_grid --num_steps 150, have you encountered this error? "Error: Mismatching phase size in tls center0 , program online".
> How should this BUG be fixed? Thank you!

I haven't had this problem before. But I'm guessing this would be related to _net.xml_ of a certain scenario, including '**tlLogic**',  the phase setting for each signalised intersection.

**Comment by Gavin-Tao** [comment]
Please be aware that this email box is not available now. If you have any contact with me, please send your emails to my current email box ***@***.***).
