### ISSUE TITLE
Different results

### ISSUE THREAD

**Issue by HappyDay-design** [Guojyjy/CoTV#5]
Hello
Thank you for uploading your models.
I have implemented your models with CoTV under the Dublin scenario. However, the results are different from those of your paper.

![image](https://github.com/Guojyjy/CoTV/assets/82990411/ad839465-57e0-4507-8fa7-21922781a6d3)

![image](https://github.com/Guojyjy/CoTV/assets/82990411/081be727-3570-4e46-b1b8-4f6ab955bae6)

As you can see, CoTVAll has the lowest performance and does not converge.

**Comment by Guojyjy** [comment]
The implementation of CoTVAll corresponds to CoTV* in our paper, in which all CAVs are trained as DRL agents. The significant increase in the number of DRL agents makes training convergence difficult. 

CoTV* can obtain good traffic performance under small-scale and synthetic road networks. Your results do not conflict with that of our paper. The 1km^2 Dublin scenario is too complex and too large-scale for CoTV*. 

Besides, your assigned computing resource (i.e., 2 CPUs) may not be enough for the training.

**Comment by HappyDay-design** [comment]
Thank you very much for your reply. It helps me a lot to understand clearly your models.

**Comment by bahramimostafa1997** [comment]
> Hello Thank you for uploading your models. I have implemented your models with CoTV under the Dublin scenario. However, the results are different from those of your paper.
> 
> ![image](https://private-user-images.githubusercontent.com/82990411/288922976-ad839465-57e0-4507-8fa7-21922781a6d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODgyMDksIm5iZiI6MTcwNDg4NzkwOSwicGF0aCI6Ii84Mjk5MDQxMS8yODg5MjI5NzYtYWQ4Mzk0NjUtNTdlMC00NTA3LThmYTctMjE5MjI3ODFhNmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDExNTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MDZkZDdjNjAxZDU1YWQ5MjU4ZjNhZTQwMTA0MzBmZGI0NjUyMzJjZmJhMTM5ZjVhNWI1NTdkOWU2NGFlOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.87FYGtVVYIfthCiiRLoYKxHKGUnzbs-6EVRN1IkrEdg)
> 
> ![image](https://private-user-images.githubusercontent.com/82990411/288923506-081be727-3570-4e46-b1b8-4f6ab955bae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODgyMDksIm5iZiI6MTcwNDg4NzkwOSwicGF0aCI6Ii84Mjk5MDQxMS8yODg5MjM1MDYtMDgxYmU3MjctMzU3MC00ZTQ2LWIxYjgtNGY2YWI5NTViYWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDExNTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyODAzZjU5MTIyMThmZGVkOWI1NDU5MjFkMDMzYjZkOTg3NDdlYjUwYzE2NTUyZGFiNDgxYmYyMDM2NGI1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sWI5ebAlucKr_7Jow1bwpUWO4dSNlQHlN4oud45WqoA)
> 
> As you can see, CoTVAll has the lowest performance and does not converge.

hi . you run this project on windows or linux? do you know that can we install flow on windows or not? tanks

**Comment by HappyDay-design** [comment]
> > Hello Thank you for uploading your models. I have implemented your models with CoTV under the Dublin scenario. However, the results are different from those of your paper.
> > ![image](https://private-user-images.githubusercontent.com/82990411/288922976-ad839465-57e0-4507-8fa7-21922781a6d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODgyMDksIm5iZiI6MTcwNDg4NzkwOSwicGF0aCI6Ii84Mjk5MDQxMS8yODg5MjI5NzYtYWQ4Mzk0NjUtNTdlMC00NTA3LThmYTctMjE5MjI3ODFhNmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDExNTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MDZkZDdjNjAxZDU1YWQ5MjU4ZjNhZTQwMTA0MzBmZGI0NjUyMzJjZmJhMTM5ZjVhNWI1NTdkOWU2NGFlOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.87FYGtVVYIfthCiiRLoYKxHKGUnzbs-6EVRN1IkrEdg)
> > ![image](https://private-user-images.githubusercontent.com/82990411/288923506-081be727-3570-4e46-b1b8-4f6ab955bae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODgyMDksIm5iZiI6MTcwNDg4NzkwOSwicGF0aCI6Ii84Mjk5MDQxMS8yODg5MjM1MDYtMDgxYmU3MjctMzU3MC00ZTQ2LWIxYjgtNGY2YWI5NTViYWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDExNTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyODAzZjU5MTIyMThmZGVkOWI1NDU5MjFkMDMzYjZkOTg3NDdlYjUwYzE2NTUyZGFiNDgxYmYyMDM2NGI1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sWI5ebAlucKr_7Jow1bwpUWO4dSNlQHlN4oud45WqoA)
> > As you can see, CoTVAll has the lowest performance and does not converge.
> 
> hi . you run this project on windows or linux? do you know that can we install flow on windows or not? tanks

Hi. I run these models on Linux.  We can not install flow on Windows, only on Linux
